name: Hugo Build and Deploy with Theme

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Hugo
        uses: actions/setup-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Install Theme
        run: |
          git clone <theme-repository-URL> themes/my-theme
          cd themes/my-theme
          # Perform any additional theme setup steps (if needed)

      - name: Set Hugo Theme
        run: |
          echo 'theme = "my-theme"' >> config.toml

      - name: Build Hugo site
        run: hugo

      - name: Deploy to Netlify
        uses: akashsis/hugo-deploy@v1.0
        with:
          deploy-url: <Netlify deployment URL>
          github-token: ${{ secrets.GITHUB_TOKEN }}


